run:
  timeout: 5m
  modules-download-mode: readonly
  build-tags:
    - "dockerT"

output:
  sort-results: true

issues:
  fix: true

linters:
  disable-all: true
  fast: false

  enable:
    - errcheck
    - ineffassign
    - gosimple
    - staticcheck
    - paralleltest
    - godot
    - gocyclo
    - dogsled
    - gci
    - gocheckcompilerdirectives
    - goconst
    - gocognit
    - gofumpt
    - gosec
    - govet
    - revive
    - misspell
    - wsl
    - goimports
