name: Bug Report
description: You encountered bug? Unexpected behavior? Open this one.
title: "[BUG]: <title>"
labels:
  - kind/bug
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
      placeholder: Put your description here.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Text
