name: Feature Request
description: You encountered bug? Unexpected behavior? Open this one.
title: "[FEATURE]: <title>"
labels:
  - kind/feature
body:
  - type: dropdown
    id: contributor
    attributes:
      label: Are you interested in contributing to the development of this feature?
      description: This will help us categorize the issue.
      options:
        - Yes
        - No
    validations:
      required: true
  - type: markdown
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: markdown
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: markdown
    attributes:
      label: Describe alternatives you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: input
    id: additional_info
    attributes:
      label: Additional Information
      description: Any other relevant information about the feature request.
